// Code generated by Scalar SDK Generator. DO NOT EDIT.

package fathomanalytics

import (
	"context"
	"net/http"
	"slices"

	"fathom-analytics/internal/requestconfig"
	"fathom-analytics/option"
)

// AccountService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewAccountService] method instead.
type AccountService struct {
	Options []option.RequestOption
}

// NewAccountService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewAccountService(opts ...option.RequestOption) (r *AccountService) {
	r = &AccountService{}
	r.Options = opts
	return
}

// Retrieve information about the account that owns the API key.
//
// **Permissions:** Requires a token with full account access (the `*` scope).
//
// **Returns:** An account object.
//
// Parameters:
//
//	ctx: Context for the request.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: Successful response
//
// Example:
//
//	err := client.Account.List(context.Background())
//	if err != nil {
//		panic(err)
//	}
func (r *AccountService) List(ctx context.Context, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	path := "account"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, nil, opts...)
	return err
}

// Retrieve metadata about the API token used to make the request, including its name, permissions (abilities), token-format version and timestamps. Your secret token value is never returned.
//
// **Permissions:** Any valid API token.
//
// **Returns:** A token object.
//
// Parameters:
//
//	ctx: Context for the request.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: Successful response
//
// Example:
//
//	err := client.Account.ListToken(context.Background())
//	if err != nil {
//		panic(err)
//	}
func (r *AccountService) ListToken(ctx context.Context, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	path := "token"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, nil, opts...)
	return err
}
