// Code generated by Scalar SDK Generator. DO NOT EDIT.

package fathomanalytics

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/marclave/fathom-go/internal/apijson"
	"github.com/marclave/fathom-go/internal/apiquery"
	"github.com/marclave/fathom-go/internal/param"
	"github.com/marclave/fathom-go/internal/requestconfig"
	"github.com/marclave/fathom-go/option"
)

// EventService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewEventService] method instead.
type EventService struct {
	Options []option.RequestOption
}

// NewEventService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewEventService(opts ...option.RequestOption) (r *EventService) {
	r = &EventService{}
	r.Options = opts
	return
}

// Return a list of all events this site owns. Events are sorted by `created_at` ascending to allow you to paginate with ease.
//
// **Permissions:** Requires read access to the site (`all-sites-readonly`, `read:{site_id}` or `manage:{site_id}`).
//
// **Returns:** A list of event objects.
//
// > **The id field is going away:** Each event still returns an `id` (the old goal code). We are removing that field on 24 September 2026. Identify events by `name` instead.
//
// > The `currency` field is returned as `null` on list responses. Set it with [Set event currency](#set-event-currency).
//
// Parameters:
//
//	ctx: Context for the request.
//	siteID: The ID of the site. This is the same string you use in your tracking code.
//	query: EventListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: Successful response
//
// Example:
//
//	err := client.Events.List(context.Background(), "CDBUGS", sdk.EventListParams{
//		Limit: sdk.F[int64](10),
//	})
//	if err != nil {
//		panic(err)
//	}
func (r *EventService) List(ctx context.Context, siteID string, query EventListParams, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	if siteID == "" {
		err = errors.New("missing required site_id parameter")
		return err
	}
	path := fmt.Sprintf("sites/%s/events", url.PathEscape(siteID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, nil, opts...)
	return err
}

// Delete an event by its name. If more than one event row shares the name, they are treated as one event and every matching row is deleted.
//
// **Permissions:** Requires write access to the site (`manage:{site_id}`).
//
// **Returns:** Returns a deleted object on success. Otherwise, this call returns an error.
//
// Parameters:
//
//	ctx: Context for the request.
//	siteID: The ID of the site. This is the same string you use in your tracking code.
//	body: EventDeleteByNameParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: Successful response
//
// Example:
//
//	err := client.Events.DeleteByName(context.Background(), "CDBUGS", sdk.EventDeleteByNameParams{
//		Name: sdk.F[string]("Purchase early access"),
//	})
//	if err != nil {
//		panic(err)
//	}
func (r *EventService) DeleteByName(ctx context.Context, siteID string, body EventDeleteByNameParams, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	if siteID == "" {
		err = errors.New("missing required site_id parameter")
		return err
	}
	path := fmt.Sprintf("sites/%s/events", url.PathEscape(siteID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, body, nil, opts...)
	return err
}

// Previously created an event. This endpoint is no longer available.
//
// **Permissions:** Requires write access to the site (`manage:{site_id}`).
//
// Parameters:
//
//	ctx: Context for the request.
//	siteID: The ID of the site. This is the same string you use in your tracking code.
//	body: EventNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: This endpoint is no longer available. Track the event on your site, then use [List events](#list-events) and [Set event currency](#set-event-currency).
//
// Example:
//
//	err := client.Events.New(context.Background(), "CDBUGS", sdk.EventNewParams{
//		Name: sdk.F[string]("Purchase early access"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
// Deprecated: this method is deprecated.
func (r *EventService) New(ctx context.Context, siteID string, body EventNewParams, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	if siteID == "" {
		err = errors.New("missing required site_id parameter")
		return err
	}
	path := fmt.Sprintf("sites/%s/events", url.PathEscape(siteID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, nil, opts...)
	return err
}

// Set the currency of an event by its name. Use this instead of updating an event by its goal code. If more than one event row shares the name, they are treated as one event and every matching row is updated.
//
// **Permissions:** Requires write access to the site (`manage:{site_id}`).
//
// **Returns:** Returns an updated object on success. Otherwise, this call returns an error.
//
// Parameters:
//
//	ctx: Context for the request.
//	siteID: The ID of the site. This is the same string you use in your tracking code.
//	body: EventSetCurrencyParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: Successful response
//
// Example:
//
//	err := client.Events.SetCurrency(context.Background(), "CDBUGS", sdk.EventSetCurrencyParams{
//		Name: sdk.F[string]("Purchase early access"),
//	})
//	if err != nil {
//		panic(err)
//	}
func (r *EventService) SetCurrency(ctx context.Context, siteID string, body EventSetCurrencyParams, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	if siteID == "" {
		err = errors.New("missing required site_id parameter")
		return err
	}
	path := fmt.Sprintf("sites/%s/events/currency", url.PathEscape(siteID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, nil, opts...)
	return err
}

// Previously returned a single event by its goal code. This endpoint is no longer available.
//
// **Permissions:** Requires read access to the site (`all-sites-readonly`, `read:{site_id}` or `manage:{site_id}`).
//
// Parameters:
//
//	ctx: Context for the request.
//	siteID: The ID of the site. This is the same string you use in your tracking code.
//	eventID: The `id` (tracking code) of the event, as returned when the event was created.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: This endpoint is no longer available. Use [List events](#list-events).
//
// Example:
//
//	err := client.Events.Get(context.Background(), "CDBUGS", "ABCDEFGH")
//	if err != nil {
//		panic(err)
//	}
//
// Deprecated: this method is deprecated.
func (r *EventService) Get(ctx context.Context, siteID string, eventID string, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	if siteID == "" {
		err = errors.New("missing required site_id parameter")
		return err
	}
	if eventID == "" {
		err = errors.New("missing required event_id parameter")
		return err
	}
	path := fmt.Sprintf("sites/%s/events/%s", url.PathEscape(siteID), url.PathEscape(eventID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, nil, opts...)
	return err
}

// Previously updated an event by its goal code. This endpoint is no longer available.
//
// **Permissions:** Requires write access to the site (`manage:{site_id}`).
//
// Parameters:
//
//	ctx: Context for the request.
//	siteID: The ID of the site. This is the same string you use in your tracking code.
//	eventID: The `id` (tracking code) of the event you wish to update.
//	body: EventUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: This endpoint is no longer available. To change an event's currency, use [Set event currency](#set-event-currency).
//
// Example:
//
//	err := client.Events.Update(context.Background(), "CDBUGS", "ABCDEFGH", sdk.EventUpdateParams{})
//	if err != nil {
//		panic(err)
//	}
//
// Deprecated: this method is deprecated.
func (r *EventService) Update(ctx context.Context, siteID string, eventID string, body EventUpdateParams, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	if siteID == "" {
		err = errors.New("missing required site_id parameter")
		return err
	}
	if eventID == "" {
		err = errors.New("missing required event_id parameter")
		return err
	}
	path := fmt.Sprintf("sites/%s/events/%s", url.PathEscape(siteID), url.PathEscape(eventID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, nil, opts...)
	return err
}

// Previously deleted an event by its goal code. This endpoint is no longer available.
//
// **Permissions:** Requires write access to the site (`manage:{site_id}`).
//
// Parameters:
//
//	ctx: Context for the request.
//	siteID: The ID of the site. This is the same string you use in your tracking code.
//	eventID: The `id` (tracking code) of the event you wish to delete.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: This endpoint is no longer available. To delete an event, use [Delete event](#delete-event-by-name) with the event name.
//
// Example:
//
//	err := client.Events.Delete(context.Background(), "CDBUGS", "ABCDEFGH")
//	if err != nil {
//		panic(err)
//	}
//
// Deprecated: this method is deprecated.
func (r *EventService) Delete(ctx context.Context, siteID string, eventID string, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	if siteID == "" {
		err = errors.New("missing required site_id parameter")
		return err
	}
	if eventID == "" {
		err = errors.New("missing required event_id parameter")
		return err
	}
	path := fmt.Sprintf("sites/%s/events/%s", url.PathEscape(siteID), url.PathEscape(eventID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, nil, opts...)
	return err
}

// Previously wiped all completion data belonging to an event. This endpoint is no longer available.
//
// Parameters:
//
//	ctx: Context for the request.
//	siteID: The ID of the site. This is the same string you use in your tracking code.
//	eventID: The `id` (tracking code) of the event.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: This endpoint has been retired and now returns `410 Gone`. It is no longer possible to wipe an event's completion data via the API.
//
// Example:
//
//	err := client.Events.Wipe(context.Background(), "CDBUGS", "ABCDEFGH")
//	if err != nil {
//		panic(err)
//	}
//
// Deprecated: this method is deprecated.
func (r *EventService) Wipe(ctx context.Context, siteID string, eventID string, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	if siteID == "" {
		err = errors.New("missing required site_id parameter")
		return err
	}
	if eventID == "" {
		err = errors.New("missing required event_id parameter")
		return err
	}
	path := fmt.Sprintf("sites/%s/events/%s/data", url.PathEscape(siteID), url.PathEscape(eventID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, nil, opts...)
	return err
}

type EventListParams struct {
	// A cursor for use in pagination, working in the opposite direction to
	// `starting_after`. `ending_before` is an object ID that defines your place in the
	// list.
	EndingBefore param.Field[string] `query:"ending_before"`
	// A limit on the number of objects to be returned, between 1 and 100.
	Limit param.Field[int64] `query:"limit"`
	// A cursor for use in pagination. `starting_after` is an object ID that defines
	// your place in the list. For example, if you make a list request and receive 10
	// objects ending with `obj_foo`, your subsequent call can include
	// `starting_after=obj_foo` to fetch the next page.
	StartingAfter param.Field[string] `query:"starting_after"`
}

// URLQuery serializes [EventListParams]'s query parameters as `url.Values`.
func (r EventListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type EventDeleteByNameParams struct {
	// The name of the event you wish to delete. Example: `Purchase early access`
	Name param.Field[string] `query:"name" api:"required"`
}

// URLQuery serializes [EventDeleteByNameParams]'s query parameters as `url.Values`.
func (r EventDeleteByNameParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type EventNewParams struct {
	// The name of the event (up to 255 characters). Example: `Purchase early access`
	Name param.Field[string] `json:"name" api:"required"`
	// The currency used for any value attached to this event's completions. If
	// omitted, defaults to `dollar`.
	Currency param.Field[EventNewParamsCurrency] `json:"currency"`
}

func (r EventNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type EventNewParamsCurrency string

const (
	EventNewParamsCurrencyDollar  EventNewParamsCurrency = "dollar"
	EventNewParamsCurrencyPound   EventNewParamsCurrency = "pound"
	EventNewParamsCurrencyEuro    EventNewParamsCurrency = "euro"
	EventNewParamsCurrencyYuan    EventNewParamsCurrency = "yuan"
	EventNewParamsCurrencyPeso    EventNewParamsCurrency = "peso"
	EventNewParamsCurrencyShekel  EventNewParamsCurrency = "shekel"
	EventNewParamsCurrencyYen     EventNewParamsCurrency = "yen"
	EventNewParamsCurrencyWon     EventNewParamsCurrency = "won"
	EventNewParamsCurrencyHryvnia EventNewParamsCurrency = "hryvnia"
	EventNewParamsCurrencyFranc   EventNewParamsCurrency = "franc"
	EventNewParamsCurrencyRupee   EventNewParamsCurrency = "rupee"
	EventNewParamsCurrencyInteger EventNewParamsCurrency = "integer"
	EventNewParamsCurrencyNone    EventNewParamsCurrency = "none"
)

func (r EventNewParamsCurrency) IsKnown() bool {
	switch r {
	case EventNewParamsCurrencyDollar, EventNewParamsCurrencyPound, EventNewParamsCurrencyEuro, EventNewParamsCurrencyYuan, EventNewParamsCurrencyPeso, EventNewParamsCurrencyShekel, EventNewParamsCurrencyYen, EventNewParamsCurrencyWon, EventNewParamsCurrencyHryvnia, EventNewParamsCurrencyFranc, EventNewParamsCurrencyRupee, EventNewParamsCurrencyInteger, EventNewParamsCurrencyNone:
		return true
	}
	return false
}

type EventSetCurrencyParams struct {
	// The currency used for any value attached to this event's completions.
	Currency param.Field[EventSetCurrencyParamsCurrency] `json:"currency" api:"required"`
	// The name of the event (up to 255 characters). Example: `Purchase early access`
	Name param.Field[string] `json:"name" api:"required"`
}

func (r EventSetCurrencyParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type EventSetCurrencyParamsCurrency string

const (
	EventSetCurrencyParamsCurrencyDollar  EventSetCurrencyParamsCurrency = "dollar"
	EventSetCurrencyParamsCurrencyPound   EventSetCurrencyParamsCurrency = "pound"
	EventSetCurrencyParamsCurrencyEuro    EventSetCurrencyParamsCurrency = "euro"
	EventSetCurrencyParamsCurrencyYuan    EventSetCurrencyParamsCurrency = "yuan"
	EventSetCurrencyParamsCurrencyPeso    EventSetCurrencyParamsCurrency = "peso"
	EventSetCurrencyParamsCurrencyShekel  EventSetCurrencyParamsCurrency = "shekel"
	EventSetCurrencyParamsCurrencyYen     EventSetCurrencyParamsCurrency = "yen"
	EventSetCurrencyParamsCurrencyWon     EventSetCurrencyParamsCurrency = "won"
	EventSetCurrencyParamsCurrencyHryvnia EventSetCurrencyParamsCurrency = "hryvnia"
	EventSetCurrencyParamsCurrencyFranc   EventSetCurrencyParamsCurrency = "franc"
	EventSetCurrencyParamsCurrencyRupee   EventSetCurrencyParamsCurrency = "rupee"
	EventSetCurrencyParamsCurrencyInteger EventSetCurrencyParamsCurrency = "integer"
	EventSetCurrencyParamsCurrencyNone    EventSetCurrencyParamsCurrency = "none"
)

func (r EventSetCurrencyParamsCurrency) IsKnown() bool {
	switch r {
	case EventSetCurrencyParamsCurrencyDollar, EventSetCurrencyParamsCurrencyPound, EventSetCurrencyParamsCurrencyEuro, EventSetCurrencyParamsCurrencyYuan, EventSetCurrencyParamsCurrencyPeso, EventSetCurrencyParamsCurrencyShekel, EventSetCurrencyParamsCurrencyYen, EventSetCurrencyParamsCurrencyWon, EventSetCurrencyParamsCurrencyHryvnia, EventSetCurrencyParamsCurrencyFranc, EventSetCurrencyParamsCurrencyRupee, EventSetCurrencyParamsCurrencyInteger, EventSetCurrencyParamsCurrencyNone:
		return true
	}
	return false
}

type EventUpdateParams struct {
	// The currency used for any value attached to this event's completions.
	Currency param.Field[EventUpdateParamsCurrency] `json:"currency"`
	// The name of the event (up to 255 characters).
	Name param.Field[string] `json:"name"`
}

func (r EventUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type EventUpdateParamsCurrency string

const (
	EventUpdateParamsCurrencyDollar  EventUpdateParamsCurrency = "dollar"
	EventUpdateParamsCurrencyPound   EventUpdateParamsCurrency = "pound"
	EventUpdateParamsCurrencyEuro    EventUpdateParamsCurrency = "euro"
	EventUpdateParamsCurrencyYuan    EventUpdateParamsCurrency = "yuan"
	EventUpdateParamsCurrencyPeso    EventUpdateParamsCurrency = "peso"
	EventUpdateParamsCurrencyShekel  EventUpdateParamsCurrency = "shekel"
	EventUpdateParamsCurrencyYen     EventUpdateParamsCurrency = "yen"
	EventUpdateParamsCurrencyWon     EventUpdateParamsCurrency = "won"
	EventUpdateParamsCurrencyHryvnia EventUpdateParamsCurrency = "hryvnia"
	EventUpdateParamsCurrencyFranc   EventUpdateParamsCurrency = "franc"
	EventUpdateParamsCurrencyRupee   EventUpdateParamsCurrency = "rupee"
	EventUpdateParamsCurrencyInteger EventUpdateParamsCurrency = "integer"
	EventUpdateParamsCurrencyNone    EventUpdateParamsCurrency = "none"
)

func (r EventUpdateParamsCurrency) IsKnown() bool {
	switch r {
	case EventUpdateParamsCurrencyDollar, EventUpdateParamsCurrencyPound, EventUpdateParamsCurrencyEuro, EventUpdateParamsCurrencyYuan, EventUpdateParamsCurrencyPeso, EventUpdateParamsCurrencyShekel, EventUpdateParamsCurrencyYen, EventUpdateParamsCurrencyWon, EventUpdateParamsCurrencyHryvnia, EventUpdateParamsCurrencyFranc, EventUpdateParamsCurrencyRupee, EventUpdateParamsCurrencyInteger, EventUpdateParamsCurrencyNone:
		return true
	}
	return false
}
