// Code generated by Scalar SDK Generator. DO NOT EDIT.

package fathomanalytics

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"fathom-analytics/internal/apijson"
	"fathom-analytics/internal/apiquery"
	"fathom-analytics/internal/param"
	"fathom-analytics/internal/requestconfig"
	"fathom-analytics/option"
)

// MilestoneService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewMilestoneService] method instead.
type MilestoneService struct {
	Options []option.RequestOption
}

// NewMilestoneService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewMilestoneService(opts ...option.RequestOption) (r *MilestoneService) {
	r = &MilestoneService{}
	r.Options = opts
	return
}

// Return a list of all milestones this site owns. Milestones are sorted by `created_at` ascending to allow you to paginate with ease.
//
// **Permissions:** Requires read access to the site (`all-sites-readonly`, `read:{site_id}` or `manage:{site_id}`).
//
// **Returns:** A list of milestone objects.
//
// Parameters:
//
//	ctx: Context for the request.
//	siteID: The ID of the site. This is the same string you use in your tracking code.
//	query: MilestoneListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: Successful response
//
// Example:
//
//	err := client.Milestones.List(context.Background(), "CDBUGS", sdk.MilestoneListParams{
//		Limit: sdk.F[int64](10),
//	})
//	if err != nil {
//		panic(err)
//	}
func (r *MilestoneService) List(ctx context.Context, siteID string, query MilestoneListParams, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	if siteID == "" {
		err = errors.New("missing required site_id parameter")
		return err
	}
	path := fmt.Sprintf("sites/%s/milestones", url.PathEscape(siteID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, nil, opts...)
	return err
}

// Create a milestone. Returns HTTP `201 Created` on success.
//
// **Permissions:** Requires write access to the site (`manage:{site_id}`).
//
// **Returns:** A milestone object.
//
// Parameters:
//
//	ctx: Context for the request.
//	siteID: The ID of the site. This is the same string you use in your tracking code.
//	body: MilestoneNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: Successful response
//
// Example:
//
//	err := client.Milestones.New(context.Background(), "CDBUGS", sdk.MilestoneNewParams{
//		MilestoneDate: sdk.F[string]("2024-01-15"),
//		Name:          sdk.F[string]("Website Redesign Launch"),
//	})
//	if err != nil {
//		panic(err)
//	}
func (r *MilestoneService) New(ctx context.Context, siteID string, body MilestoneNewParams, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	if siteID == "" {
		err = errors.New("missing required site_id parameter")
		return err
	}
	path := fmt.Sprintf("sites/%s/milestones", url.PathEscape(siteID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, nil, opts...)
	return err
}

// Return a single milestone.
//
// **Permissions:** Requires read access to the site (`all-sites-readonly`, `read:{site_id}` or `manage:{site_id}`).
//
// **Returns:** A milestone object.
//
// Parameters:
//
//	ctx: Context for the request.
//	siteID: The ID of the site. This is the same string you use in your tracking code.
//	milestoneID: The `id` (UUID) of the milestone you wish to retrieve.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: Successful response
//
// Example:
//
//	err := client.Milestones.Get(context.Background(), "CDBUGS", "ddc9cdff-ab83-41fa-96c6-dfb276a862e7")
//	if err != nil {
//		panic(err)
//	}
func (r *MilestoneService) Get(ctx context.Context, siteID string, milestoneID string, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	if siteID == "" {
		err = errors.New("missing required site_id parameter")
		return err
	}
	if milestoneID == "" {
		err = errors.New("missing required milestone_id parameter")
		return err
	}
	path := fmt.Sprintf("sites/%s/milestones/%s", url.PathEscape(siteID), url.PathEscape(milestoneID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, nil, opts...)
	return err
}

// Update a milestone. Both `name` and `milestone_date` are required.
//
// **Permissions:** Requires write access to the site (`manage:{site_id}`).
//
// **Returns:** A milestone object.
//
// Parameters:
//
//	ctx: Context for the request.
//	siteID: The ID of the site. This is the same string you use in your tracking code.
//	milestoneID: The `id` (UUID) of the milestone you wish to update.
//	body: MilestoneUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: Successful response
//
// Example:
//
//	err := client.Milestones.Update(context.Background(), "CDBUGS", "ddc9cdff-ab83-41fa-96c6-dfb276a862e7", sdk.MilestoneUpdateParams{
//		MilestoneDate: sdk.F[string]("2024-01-20"),
//		Name:          sdk.F[string]("Website Redesign Launch v2"),
//	})
//	if err != nil {
//		panic(err)
//	}
func (r *MilestoneService) Update(ctx context.Context, siteID string, milestoneID string, body MilestoneUpdateParams, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	if siteID == "" {
		err = errors.New("missing required site_id parameter")
		return err
	}
	if milestoneID == "" {
		err = errors.New("missing required milestone_id parameter")
		return err
	}
	path := fmt.Sprintf("sites/%s/milestones/%s", url.PathEscape(siteID), url.PathEscape(milestoneID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, nil, opts...)
	return err
}

// Delete a milestone. Careful: you can't undo this, and neither can we.
//
// **Permissions:** Requires write access to the site (`manage:{site_id}`).
//
// **Returns:** Returns a deleted object on success. Otherwise, this call returns an error.
//
// Parameters:
//
//	ctx: Context for the request.
//	siteID: The ID of the site. This is the same string you use in your tracking code.
//	milestoneID: The `id` (UUID) of the milestone you wish to delete.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: Successful response
//
// Example:
//
//	err := client.Milestones.Delete(context.Background(), "CDBUGS", "ddc9cdff-ab83-41fa-96c6-dfb276a862e7")
//	if err != nil {
//		panic(err)
//	}
func (r *MilestoneService) Delete(ctx context.Context, siteID string, milestoneID string, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	if siteID == "" {
		err = errors.New("missing required site_id parameter")
		return err
	}
	if milestoneID == "" {
		err = errors.New("missing required milestone_id parameter")
		return err
	}
	path := fmt.Sprintf("sites/%s/milestones/%s", url.PathEscape(siteID), url.PathEscape(milestoneID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, nil, opts...)
	return err
}

type MilestoneListParams struct {
	// A cursor for use in pagination, working in the opposite direction to
	// `starting_after`. `ending_before` is an object ID that defines your place in the
	// list.
	EndingBefore param.Field[string] `query:"ending_before"`
	// A limit on the number of objects to be returned, between 1 and 100.
	Limit param.Field[int64] `query:"limit"`
	// A cursor for use in pagination. `starting_after` is an object ID that defines
	// your place in the list. For example, if you make a list request and receive 10
	// objects ending with `obj_foo`, your subsequent call can include
	// `starting_after=obj_foo` to fetch the next page.
	StartingAfter param.Field[string] `query:"starting_after"`
}

// URLQuery serializes [MilestoneListParams]'s query parameters as `url.Values`.
func (r MilestoneListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type MilestoneNewParams struct {
	// The date of the milestone in `YYYY-MM-DD` format.
	MilestoneDate param.Field[string] `json:"milestone_date" api:"required"`
	// The name of the milestone (up to 30 characters).
	Name param.Field[string] `json:"name" api:"required"`
}

func (r MilestoneNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type MilestoneUpdateParams struct {
	// The date of the milestone in `YYYY-MM-DD` format.
	MilestoneDate param.Field[string] `json:"milestone_date" api:"required"`
	// The name of the milestone (up to 30 characters).
	Name param.Field[string] `json:"name" api:"required"`
}

func (r MilestoneUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}
