// Code generated by Scalar SDK Generator. DO NOT EDIT.

package fathomanalytics

import (
	"context"
	"net/http"
	"net/url"
	"slices"

	"fathom-analytics/internal/apiquery"
	"fathom-analytics/internal/param"
	"fathom-analytics/internal/requestconfig"
	"fathom-analytics/option"
)

// ReportService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewReportService] method instead.
type ReportService struct {
	Options []option.RequestOption
}

// NewReportService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewReportService(opts ...option.RequestOption) (r *ReportService) {
	r = &ReportService{}
	r.Options = opts
	return
}

// Build a custom report. Group and filter on the fields you care about.
//
// **Permissions:** Requires read access to the relevant site (`all-sites-readonly`, `read:{site_id}` or `manage:{site_id}`).
//
// **Returns:** Returns an array of objects. The properties of each object vary based on the aggregates and groupings you've asked for. All numeric values are returned as strings.
//
// > This API endpoint is only accurate on data from March 2021 onwards. Before then, we did not tie browser, country, pathname, etc. together, so we have no way to offer this advanced filtering on that data.
//
// > Grouped reports (`field_grouping`) default to 500 rows unless you set `limit`. The maximum is 1000, and this endpoint has no pagination. BI tools such as Looker Studio / Data Studio that fire many aggregations at once will hit the [concurrency cap](/api/v1/rate-limits), not the row cap. Space those requests, cache one extract per period, or raise the API plan.
//
// > **Goal codes are no longer available:** Reporting on an event by its goal code (`entity_id` with `entity=event`) is no longer available. Report on events using `site_id` and `entity_name` instead. Pageview reporting, where `entity_id` is the site `id`, is unaffected.
//
// #### Filtering
//
// Filters are supplied as a JSON array. Each filter is an object with a `property`, an `operator` and a string `value`. You can add as many filters as you like; see the examples in the code panel.
//
// We support the following operators:
//
// - `is`: exact match
// - `is not`: everything except an exact match
// - `is like`: contains the term (supports wildcards `*`)
// - `is not like`: does not contain the term
// - `matching`: matches a regular expression (regex) pattern
// - `not matching`: does not match a regex pattern
//
// **Operator availability depends on the field.** Text-style fields support all six operators; categorical fields support only `is` and `is not`:
//
// - **All six operators:** `domain`, `hostname`, `pathname`, `entry_page`, `exit_page`, `referrer_hostname`, `referrer_pathname`, `referrer_source`, `ref`, `utm_campaign`, `utm_source`, `utm_medium`, `utm_content`, `utm_term`
// - **`is` / `is not` only:** `device_type`, `operating_system`, `browser`, `country_code`, `city`, `state`, `region`
//
// Note: `domain` can be filtered on but not grouped by, while `keyword` can be grouped by but not filtered on.
//
// ##### Entry and exit pages
//
// `entry_page` is the pathname of the first pageview in a visit. `exit_page` is the pathname of the last pageview before the visitor leaves. Both are session-level fields. They mirror the Entry Pages and Exit Pages reports on your dashboard and work for both `field_grouping` and `filters`.
//
// When you filter by `entry_page`, only visits that *entered* on that page are included. A visitor who lands on `/home` and later views `/pricing` is excluded by `{"property": "entry_page", "operator": "is", "value": "/pricing"}`, but included when filtering on `pathname` instead.
//
// ##### Regex examples
//
// With `matching` / `not matching` you can build sophisticated filters:
//
// - `^/(about|contact|pricing)$`: match only /about, /contact and /pricing
// - `^/(about|contact|pricing)`: match paths starting with those
// - `^/blog/\d{4}/\d{2}/`: match blog URLs like /blog/2025/07/my-post
// - `^/products/[^/]+/$`: match product category pages
//
// Parameters:
//
//	ctx: Context for the request.
//	query: ReportAggregationParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: Successful response
//
// Example:
//
//	err := client.Reports.Aggregation(context.Background(), sdk.ReportAggregationParams{
//		Aggregates: sdk.F[string]("pageviews"),
//		Entity:     sdk.F[sdk.ReportAggregationParamsEntity](sdk.ReportAggregationParamsEntity("pageview")),
//	})
//	if err != nil {
//		panic(err)
//	}
func (r *ReportService) Aggregation(ctx context.Context, query ReportAggregationParams, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	path := "aggregations"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, nil, opts...)
	return err
}

// Returns the total number of current visitors on a site. The detailed view also returns the top 150 pages and top 150 referrers.
//
// **Permissions:** Requires read access to the site (`all-sites-readonly`, `read:{site_id}` or `manage:{site_id}`).
//
// **Returns:** The current visitor count, with an optional detailed breakdown.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: ReportCurrentVisitorsParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: Simple
//
// Example:
//
//	err := client.Reports.CurrentVisitors(context.Background(), sdk.ReportCurrentVisitorsParams{
//		SiteID:   sdk.F[string]("CDBUGS"),
//		Detailed: sdk.F[bool](false),
//	})
//	if err != nil {
//		panic(err)
//	}
func (r *ReportService) CurrentVisitors(ctx context.Context, query ReportCurrentVisitorsParams, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	path := "current_visitors"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, nil, opts...)
	return err
}

type ReportAggregationParams struct {
	// The aggregates you wish to include, separated by a comma.
	//
	// Supported values for **pageview** entities: `visits`, `uniques`, `pageviews`,
	// `avg_duration` and `bounce_rate`. The difference between "visits" and "uniques"
	// is that visits are unique site visits whilst uniques are unique page visits.
	//
	// Supported values for **event** entities: `conversions`, `unique_conversions` and
	// `value` (value is returned in cents).
	Aggregates param.Field[string] `query:"aggregates" api:"required"`
	// The entity you want to report on. Events are treated separately from pageviews.
	// Supported values: `pageview` and `event`.
	Entity param.Field[ReportAggregationParamsEntity] `query:"entity" api:"required"`
	// Timestamp (e.g. `2022-04-01 15:31:00`). Should match the timezone you're
	// reporting in. Defaults to the entity's first recorded data.
	DateFrom param.Field[string] `query:"date_from"`
	// By default, we don't do any date grouping and return total aggregations.
	// Override this with `hour`, `day`, `month` or `year`. Note: `hour` grouping is
	// only supported for date ranges of up to 7 days.
	DateGrouping param.Field[ReportAggregationParamsDateGrouping] `query:"date_grouping"`
	// Timestamp (e.g. `2022-04-01 15:31:00`). Should match the timezone you're
	// reporting in. Default: now.
	DateTo param.Field[string] `query:"date_to"`
	// When `entity` is `pageview`, this is the `id` of the site you want to aggregate
	// on. When `entity` is `event`, do not pass a goal code here. Use `site_id` and
	// `entity_name` instead. Pageview usage is unchanged.
	//
	// **Required when entity is "pageview".**
	EntityID param.Field[string] `query:"entity_id"`
	// The name of the event you want to report on. Example: `purchase`.
	//
	// **Required when entity is "event" and entity_id is omitted.**
	EntityName param.Field[string] `query:"entity_name"`
	// The fields you want to group by, separated by a comma (e.g.
	// `hostname,pathname`). Supported values: `hostname`, `pathname`, `entry_page`,
	// `exit_page`, `referrer_hostname`, `referrer_pathname`, `referrer_source`,
	// `browser`, `country_code`, `city`, `state`, `region`, `device_type`,
	// `operating_system`, `utm_campaign`, `utm_content`, `utm_medium`, `utm_source`,
	// `utm_term`, `keyword` and `ref`.
	FieldGrouping param.Field[string] `query:"field_grouping"`
	// A JSON-encoded array of filter objects. See the filtering reference below for
	// the full list of supported properties and operators. Each filter's `value` must
	// be a string.
	Filters param.Field[string] `query:"filters"`
	// Optional integer from `1` to `1000` inclusive.
	//
	// **Default.** When `field_grouping` is set and you omit `limit`, we return at
	// most 500 rows. When `field_grouping` is omitted, there is no default row cap.
	// `date_grouping` alone does not trigger the 500 default.
	//
	// **Maximum.** A `limit` above 1000 returns HTTP 400 with an `errors.limit`
	// validation message. There is no pagination on this endpoint, so you cannot walk
	// past 1000 grouped rows with a cursor. Narrow the result with `filters` and/or a
	// shorter `date_from` / `date_to`, then issue more requests.
	Limit param.Field[int64] `query:"limit"`
	// The `id` of the site the event belongs to.
	//
	// **Required when entity is "event" and entity_id is omitted.**
	SiteID param.Field[string] `query:"site_id"`
	// The field you want to sort by, in the format `field:asc|desc`. You can use any
	// field present in `aggregates` or `field_grouping`. When using `date_grouping`,
	// you can also sort by `timestamp:asc` or `timestamp:desc`. Example:
	// `pageviews:desc`
	SortBy param.Field[string] `query:"sort_by"`
	// **Deprecated.** We now report using each site's configured timezone by default.
	// If provided, this [TZ database
	// name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) overrides
	// the site's timezone for this request. We'll be removing this parameter in the
	// future.
	Timezone param.Field[string] `query:"timezone"`
}

// URLQuery serializes [ReportAggregationParams]'s query parameters as `url.Values`.
func (r ReportAggregationParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type ReportAggregationParamsEntity string

const (
	ReportAggregationParamsEntityPageview ReportAggregationParamsEntity = "pageview"
	ReportAggregationParamsEntityEvent    ReportAggregationParamsEntity = "event"
)

func (r ReportAggregationParamsEntity) IsKnown() bool {
	switch r {
	case ReportAggregationParamsEntityPageview, ReportAggregationParamsEntityEvent:
		return true
	}
	return false
}

type ReportAggregationParamsDateGrouping string

const (
	ReportAggregationParamsDateGroupingHour  ReportAggregationParamsDateGrouping = "hour"
	ReportAggregationParamsDateGroupingDay   ReportAggregationParamsDateGrouping = "day"
	ReportAggregationParamsDateGroupingMonth ReportAggregationParamsDateGrouping = "month"
	ReportAggregationParamsDateGroupingYear  ReportAggregationParamsDateGrouping = "year"
)

func (r ReportAggregationParamsDateGrouping) IsKnown() bool {
	switch r {
	case ReportAggregationParamsDateGroupingHour, ReportAggregationParamsDateGroupingDay, ReportAggregationParamsDateGroupingMonth, ReportAggregationParamsDateGroupingYear:
		return true
	}
	return false
}

type ReportCurrentVisitorsParams struct {
	// The `id` of the site. Example: `CDBUGS`
	SiteID param.Field[string] `query:"site_id" api:"required"`
	// Set to `true` for a detailed breakdown of pages and referrers. Otherwise you'll
	// only get a count.
	Detailed param.Field[bool] `query:"detailed"`
}

// URLQuery serializes [ReportCurrentVisitorsParams]'s query parameters as `url.Values`.
func (r ReportCurrentVisitorsParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}
