// Code generated by Scalar SDK Generator. DO NOT EDIT.

package fathomanalytics

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"fathom-analytics/internal/apijson"
	"fathom-analytics/internal/apiquery"
	"fathom-analytics/internal/param"
	"fathom-analytics/internal/requestconfig"
	"fathom-analytics/option"
)

// SiteService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewSiteService] method instead.
type SiteService struct {
	Options []option.RequestOption
}

// NewSiteService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewSiteService(opts ...option.RequestOption) (r *SiteService) {
	r = &SiteService{}
	r.Options = opts
	return
}

// Return a list of all sites this API key owns. Sites are sorted by `created_at` ascending to allow you to paginate with ease.
//
// **Permissions:** Requires read access to all sites (`all-sites-readonly`) or full account access.
//
// **Returns:** A list of site objects.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: SiteListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: Successful response
//
// Example:
//
//	err := client.Sites.List(context.Background(), sdk.SiteListParams{
//		Limit: sdk.F[int64](10),
//	})
//	if err != nil {
//		panic(err)
//	}
func (r *SiteService) List(ctx context.Context, query SiteListParams, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	path := "sites"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, nil, opts...)
	return err
}

// Create a site.
//
// **Permissions:** Requires full account access (`*`).
//
// **Returns:** A site object.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: SiteNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: Successful response
//
// Example:
//
//	err := client.Sites.New(context.Background(), sdk.SiteNewParams{
//		Name: sdk.F[string]("Bugs Bunny Portfolio"),
//	})
//	if err != nil {
//		panic(err)
//	}
func (r *SiteService) New(ctx context.Context, body SiteNewParams, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	path := "sites"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, nil, opts...)
	return err
}

// Return a single site.
//
// **Permissions:** Requires read access to the site (`all-sites-readonly`, `read:{site_id}` or `manage:{site_id}`).
//
// **Returns:** A site object.
//
// Parameters:
//
//	ctx: Context for the request.
//	siteID: The ID of the site. This is the same string you use in your tracking code.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: Successful response
//
// Example:
//
//	err := client.Sites.Get(context.Background(), "CDBUGS")
//	if err != nil {
//		panic(err)
//	}
func (r *SiteService) Get(ctx context.Context, siteID string, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	if siteID == "" {
		err = errors.New("missing required site_id parameter")
		return err
	}
	path := fmt.Sprintf("sites/%s", url.PathEscape(siteID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, nil, opts...)
	return err
}

// Update a site. Send only the fields you want to change.
//
// **Permissions:** Requires write access to the site (`manage:{site_id}`).
//
// **Returns:** A site object.
//
// Parameters:
//
//	ctx: Context for the request.
//	siteID: The ID of the site. This is the same string you use in your tracking code.
//	body: SiteUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: Successful response
//
// Example:
//
//	err := client.Sites.Update(context.Background(), "CDBUGS", sdk.SiteUpdateParams{})
//	if err != nil {
//		panic(err)
//	}
func (r *SiteService) Update(ctx context.Context, siteID string, body SiteUpdateParams, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	if siteID == "" {
		err = errors.New("missing required site_id parameter")
		return err
	}
	path := fmt.Sprintf("sites/%s", url.PathEscape(siteID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, nil, opts...)
	return err
}

// Delete a site. Careful: you can't undo this, and neither can we.
//
// **Permissions:** Requires full account access (`*`).
//
// **Returns:** Returns a deleted object on success. Otherwise, this call returns an error.
//
// Parameters:
//
//	ctx: Context for the request.
//	siteID: The ID of the site. This is the same string you use in your tracking code.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: Successful response
//
// Example:
//
//	err := client.Sites.Delete(context.Background(), "CDBUGS")
//	if err != nil {
//		panic(err)
//	}
func (r *SiteService) Delete(ctx context.Context, siteID string, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	if siteID == "" {
		err = errors.New("missing required site_id parameter")
		return err
	}
	path := fmt.Sprintf("sites/%s", url.PathEscape(siteID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, nil, opts...)
	return err
}

// Previously wiped all pageviews and event completions from a website. This endpoint is no longer available.
//
// Parameters:
//
//	ctx: Context for the request.
//	siteID: The ID of the site. This is the same string you use in your tracking code.
//	opts: Options to apply to this request.
//
// Returns:
//
//	error: This endpoint has been retired and now returns `410 Gone`. It is no longer possible to wipe a site's data via the API.
//
// Example:
//
//	err := client.Sites.Wipe(context.Background(), "CDBUGS")
//	if err != nil {
//		panic(err)
//	}
//
// Deprecated: this method is deprecated.
func (r *SiteService) Wipe(ctx context.Context, siteID string, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	if siteID == "" {
		err = errors.New("missing required site_id parameter")
		return err
	}
	path := fmt.Sprintf("sites/%s/data", url.PathEscape(siteID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, nil, opts...)
	return err
}

type SiteListParams struct {
	// A cursor for use in pagination, working in the opposite direction to
	// `starting_after`. `ending_before` is an object ID that defines your place in the
	// list.
	EndingBefore param.Field[string] `query:"ending_before"`
	// A limit on the number of objects to be returned, between 1 and 100.
	Limit param.Field[int64] `query:"limit"`
	// A cursor for use in pagination. `starting_after` is an object ID that defines
	// your place in the list. For example, if you make a list request and receive 10
	// objects ending with `obj_foo`, your subsequent call can include
	// `starting_after=obj_foo` to fetch the next page.
	StartingAfter param.Field[string] `query:"starting_after"`
}

// URLQuery serializes [SiteListParams]'s query parameters as `url.Values`.
func (r SiteListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type SiteNewParams struct {
	// The name of the website. Any string (up to 255 characters) is acceptable, and it
	// doesn't have to match the website URL. Example: `Daffy's Website`
	Name param.Field[string] `json:"name" api:"required"`
	// Set to `true` to allow this site to track multiple domains.
	MultiDomain param.Field[bool] `json:"multi_domain"`
	// How multi-domain data is grouped. Supported values are `combined` (report all
	// domains together) or `separate` (report each domain individually).
	//
	// **Required if multi_domain is true.**
	MultiDomainOption param.Field[SiteNewParamsMultiDomainOption] `json:"multi_domain_option"`
	// When sharing is set to `private`, you must also send a password to access the
	// site with (up to 255 characters).
	//
	// **Required if sharing is private.**
	SharePassword param.Field[string] `json:"share_password"`
	// The sharing configuration. Supported values are `none`, `private` or `public`.
	Sharing param.Field[SiteNewParamsSharing] `json:"sharing"`
	// The site's reporting timezone as a [TZ database
	// name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) (e.g.
	// `America/New_York`). If omitted, the site inherits your account's default
	// timezone.
	Timezone param.Field[string] `json:"timezone"`
}

func (r SiteNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type SiteNewParamsSharing string

const (
	SiteNewParamsSharingNone    SiteNewParamsSharing = "none"
	SiteNewParamsSharingPrivate SiteNewParamsSharing = "private"
	SiteNewParamsSharingPublic  SiteNewParamsSharing = "public"
)

func (r SiteNewParamsSharing) IsKnown() bool {
	switch r {
	case SiteNewParamsSharingNone, SiteNewParamsSharingPrivate, SiteNewParamsSharingPublic:
		return true
	}
	return false
}

type SiteNewParamsMultiDomainOption string

const (
	SiteNewParamsMultiDomainOptionCombined SiteNewParamsMultiDomainOption = "combined"
	SiteNewParamsMultiDomainOptionSeparate SiteNewParamsMultiDomainOption = "separate"
)

func (r SiteNewParamsMultiDomainOption) IsKnown() bool {
	switch r {
	case SiteNewParamsMultiDomainOptionCombined, SiteNewParamsMultiDomainOptionSeparate:
		return true
	}
	return false
}

type SiteUpdateParams struct {
	// Set to `true` to allow this site to track multiple domains.
	MultiDomain param.Field[bool] `json:"multi_domain"`
	// How multi-domain data is grouped: `combined` or `separate`.
	//
	// **Required if multi_domain is true.**
	MultiDomainOption param.Field[SiteUpdateParamsMultiDomainOption] `json:"multi_domain_option"`
	// The name of the website (up to 255 characters).
	Name param.Field[string] `json:"name"`
	// When sharing is set to `private`, you must also send a password to access the
	// site with (up to 255 characters).
	//
	// **Required if sharing is private.**
	SharePassword param.Field[string] `json:"share_password"`
	// The sharing configuration. Supported values are `none`, `private` or `public`.
	Sharing param.Field[SiteUpdateParamsSharing] `json:"sharing"`
	// The site's reporting timezone as a [TZ database
	// name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) (e.g.
	// `America/New_York`). Reporting for this site will use this timezone.
	Timezone param.Field[string] `json:"timezone"`
}

func (r SiteUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type SiteUpdateParamsSharing string

const (
	SiteUpdateParamsSharingNone    SiteUpdateParamsSharing = "none"
	SiteUpdateParamsSharingPrivate SiteUpdateParamsSharing = "private"
	SiteUpdateParamsSharingPublic  SiteUpdateParamsSharing = "public"
)

func (r SiteUpdateParamsSharing) IsKnown() bool {
	switch r {
	case SiteUpdateParamsSharingNone, SiteUpdateParamsSharingPrivate, SiteUpdateParamsSharingPublic:
		return true
	}
	return false
}

type SiteUpdateParamsMultiDomainOption string

const (
	SiteUpdateParamsMultiDomainOptionCombined SiteUpdateParamsMultiDomainOption = "combined"
	SiteUpdateParamsMultiDomainOptionSeparate SiteUpdateParamsMultiDomainOption = "separate"
)

func (r SiteUpdateParamsMultiDomainOption) IsKnown() bool {
	switch r {
	case SiteUpdateParamsMultiDomainOptionCombined, SiteUpdateParamsMultiDomainOptionSeparate:
		return true
	}
	return false
}
