// Code generated by Scalar SDK Generator. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"sync"
	"time"

	sdk "github.com/marclave/fathom-go"
	"github.com/marclave/fathom-go/option"
)

// Smoke test: calls every generated operation once to confirm the SDK can reach each endpoint.
// Run it from this repo with `go run tests/smoke-test.go`. The generator also runs this file
// against a mock server and reads the JSON report produced via SCALAR_SMOKE_REPORT.
var client = sdk.NewClient(option.WithBearerAuth("test"), option.WithHeader("Authorization", "Bearer test"))

type smokeResult struct {
	Operation  string `json:"operation"`
	Method     string `json:"method"`
	Path       string `json:"path"`
	Label      string `json:"label,omitempty"`
	Status     string `json:"status"`
	DurationMs int64  `json:"durationMs"`
	Error      string `json:"error,omitempty"`
}

// Label says which of an operation's two calls this is — "required params" or "all params".
// It is empty when the operation contributed a single case.
type smokeCase struct {
	Operation string
	Method    string
	Path      string
	Label     string
	Run       func()
}

func _smokeCase0() {
	err := client.Account.List(context.Background())
	if err != nil {
		panic(err)
	}
}

func _smokeCase1() {
	err := client.Account.ListToken(context.Background())
	if err != nil {
		panic(err)
	}
}

func _smokeCase2() {
	err := client.Sites.List(context.Background(), sdk.SiteListParams{
		Limit: sdk.F[int64](10),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase3() {
	err := client.Sites.List(context.Background(), sdk.SiteListParams{
		EndingBefore:  sdk.F[string](""),
		Limit:         sdk.F[int64](10),
		StartingAfter: sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase4() {
	err := client.Sites.New(context.Background(), sdk.SiteNewParams{
		Name: sdk.F[string]("Bugs Bunny Portfolio"),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase5() {
	err := client.Sites.New(context.Background(), sdk.SiteNewParams{
		Name:          sdk.F[string]("Bugs Bunny Portfolio"),
		MultiDomain:   sdk.F[bool](false),
		SharePassword: sdk.F[string](""),
		Timezone:      sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase6() {
	err := client.Sites.Get(context.Background(), "CDBUGS")
	if err != nil {
		panic(err)
	}
}

func _smokeCase7() {
	err := client.Sites.Update(context.Background(), "CDBUGS", sdk.SiteUpdateParams{})
	if err != nil {
		panic(err)
	}
}

func _smokeCase8() {
	err := client.Sites.Update(context.Background(), "CDBUGS", sdk.SiteUpdateParams{
		MultiDomain:   sdk.F[bool](false),
		Name:          sdk.F[string]("Acme Holdings Inc"),
		SharePassword: sdk.F[string](""),
		Timezone:      sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase9() {
	err := client.Sites.Delete(context.Background(), "CDBUGS")
	if err != nil {
		panic(err)
	}
}

func _smokeCase10() {
	err := client.Sites.Wipe(context.Background(), "CDBUGS")
	if err != nil {
		panic(err)
	}
}

func _smokeCase11() {
	err := client.Events.List(context.Background(), "CDBUGS", sdk.EventListParams{
		Limit: sdk.F[int64](10),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase12() {
	err := client.Events.List(context.Background(), "CDBUGS", sdk.EventListParams{
		EndingBefore:  sdk.F[string](""),
		Limit:         sdk.F[int64](10),
		StartingAfter: sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase13() {
	err := client.Events.DeleteByName(context.Background(), "CDBUGS", sdk.EventDeleteByNameParams{
		Name: sdk.F[string]("Purchase early access"),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase14() {
	err := client.Events.New(context.Background(), "CDBUGS", sdk.EventNewParams{
		Name: sdk.F[string]("Purchase early access"),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase15() {
	err := client.Events.SetCurrency(context.Background(), "CDBUGS", sdk.EventSetCurrencyParams{
		Name: sdk.F[string]("Purchase early access"),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase16() {
	err := client.Events.Get(context.Background(), "CDBUGS", "ABCDEFGH")
	if err != nil {
		panic(err)
	}
}

func _smokeCase17() {
	err := client.Events.Update(context.Background(), "CDBUGS", "ABCDEFGH", sdk.EventUpdateParams{})
	if err != nil {
		panic(err)
	}
}

func _smokeCase18() {
	err := client.Events.Update(context.Background(), "CDBUGS", "ABCDEFGH", sdk.EventUpdateParams{
		Name: sdk.F[string]("Purchase early access (live)"),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase19() {
	err := client.Events.Delete(context.Background(), "CDBUGS", "ABCDEFGH")
	if err != nil {
		panic(err)
	}
}

func _smokeCase20() {
	err := client.Events.Wipe(context.Background(), "CDBUGS", "ABCDEFGH")
	if err != nil {
		panic(err)
	}
}

func _smokeCase21() {
	err := client.Milestones.List(context.Background(), "CDBUGS", sdk.MilestoneListParams{
		Limit: sdk.F[int64](10),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase22() {
	err := client.Milestones.List(context.Background(), "CDBUGS", sdk.MilestoneListParams{
		EndingBefore:  sdk.F[string](""),
		Limit:         sdk.F[int64](10),
		StartingAfter: sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase23() {
	err := client.Milestones.New(context.Background(), "CDBUGS", sdk.MilestoneNewParams{
		MilestoneDate: sdk.F[string]("2024-01-15"),
		Name:          sdk.F[string]("Website Redesign Launch"),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase24() {
	err := client.Milestones.Get(context.Background(), "CDBUGS", "ddc9cdff-ab83-41fa-96c6-dfb276a862e7")
	if err != nil {
		panic(err)
	}
}

func _smokeCase25() {
	err := client.Milestones.Update(context.Background(), "CDBUGS", "ddc9cdff-ab83-41fa-96c6-dfb276a862e7", sdk.MilestoneUpdateParams{
		MilestoneDate: sdk.F[string]("2024-01-20"),
		Name:          sdk.F[string]("Website Redesign Launch v2"),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase26() {
	err := client.Milestones.Delete(context.Background(), "CDBUGS", "ddc9cdff-ab83-41fa-96c6-dfb276a862e7")
	if err != nil {
		panic(err)
	}
}

func _smokeCase27() {
	err := client.Reports.Aggregation(context.Background(), sdk.ReportAggregationParams{
		Aggregates: sdk.F[string]("pageviews"),
		Entity:     sdk.F[sdk.ReportAggregationParamsEntity](sdk.ReportAggregationParamsEntity("pageview")),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase28() {
	err := client.Reports.Aggregation(context.Background(), sdk.ReportAggregationParams{
		Aggregates:    sdk.F[string]("pageviews"),
		Entity:        sdk.F[sdk.ReportAggregationParamsEntity](sdk.ReportAggregationParamsEntity("pageview")),
		DateFrom:      sdk.F[string](""),
		DateGrouping:  sdk.F[sdk.ReportAggregationParamsDateGrouping](sdk.ReportAggregationParamsDateGrouping("hour")),
		DateTo:        sdk.F[string](""),
		EntityID:      sdk.F[string]("CDBUGS"),
		EntityName:    sdk.F[string](""),
		FieldGrouping: sdk.F[string](""),
		Filters:       sdk.F[string](""),
		Limit:         sdk.F[int64](0),
		SiteID:        sdk.F[string](""),
		SortBy:        sdk.F[string](""),
		Timezone:      sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}
}

func _smokeCase29() {
	err := client.Reports.CurrentVisitors(context.Background(), sdk.ReportCurrentVisitorsParams{
		SiteID:   sdk.F[string]("CDBUGS"),
		Detailed: sdk.F[bool](false),
	})
	if err != nil {
		panic(err)
	}
}

var cases = []smokeCase{
	{
		Operation: "list",
		Method:    "GET",
		Path:      "/account",
		Run:       _smokeCase0,
	},

	{
		Operation: "listToken",
		Method:    "GET",
		Path:      "/token",
		Run:       _smokeCase1,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/sites",
		Label:     "required params",
		Run:       _smokeCase2,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/sites",
		Label:     "all params",
		Run:       _smokeCase3,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/sites",
		Label:     "required params",
		Run:       _smokeCase4,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/sites",
		Label:     "all params",
		Run:       _smokeCase5,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/sites/{site_id}",
		Run:       _smokeCase6,
	},

	{
		Operation: "update",
		Method:    "POST",
		Path:      "/sites/{site_id}",
		Label:     "required params",
		Run:       _smokeCase7,
	},

	{
		Operation: "update",
		Method:    "POST",
		Path:      "/sites/{site_id}",
		Label:     "all params",
		Run:       _smokeCase8,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/sites/{site_id}",
		Run:       _smokeCase9,
	},

	{
		Operation: "wipe",
		Method:    "DELETE",
		Path:      "/sites/{site_id}/data",
		Run:       _smokeCase10,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/sites/{site_id}/events",
		Label:     "required params",
		Run:       _smokeCase11,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/sites/{site_id}/events",
		Label:     "all params",
		Run:       _smokeCase12,
	},

	{
		Operation: "deleteByName",
		Method:    "DELETE",
		Path:      "/sites/{site_id}/events",
		Run:       _smokeCase13,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/sites/{site_id}/events",
		Run:       _smokeCase14,
	},

	{
		Operation: "setCurrency",
		Method:    "POST",
		Path:      "/sites/{site_id}/events/currency",
		Run:       _smokeCase15,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/sites/{site_id}/events/{event_id}",
		Run:       _smokeCase16,
	},

	{
		Operation: "update",
		Method:    "POST",
		Path:      "/sites/{site_id}/events/{event_id}",
		Label:     "required params",
		Run:       _smokeCase17,
	},

	{
		Operation: "update",
		Method:    "POST",
		Path:      "/sites/{site_id}/events/{event_id}",
		Label:     "all params",
		Run:       _smokeCase18,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/sites/{site_id}/events/{event_id}",
		Run:       _smokeCase19,
	},

	{
		Operation: "wipe",
		Method:    "DELETE",
		Path:      "/sites/{site_id}/events/{event_id}/data",
		Run:       _smokeCase20,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/sites/{site_id}/milestones",
		Label:     "required params",
		Run:       _smokeCase21,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/sites/{site_id}/milestones",
		Label:     "all params",
		Run:       _smokeCase22,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/sites/{site_id}/milestones",
		Run:       _smokeCase23,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/sites/{site_id}/milestones/{milestone_id}",
		Run:       _smokeCase24,
	},

	{
		Operation: "update",
		Method:    "POST",
		Path:      "/sites/{site_id}/milestones/{milestone_id}",
		Run:       _smokeCase25,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/sites/{site_id}/milestones/{milestone_id}",
		Run:       _smokeCase26,
	},

	{
		Operation: "aggregation",
		Method:    "GET",
		Path:      "/aggregations",
		Label:     "required params",
		Run:       _smokeCase27,
	},

	{
		Operation: "aggregation",
		Method:    "GET",
		Path:      "/aggregations",
		Label:     "all params",
		Run:       _smokeCase28,
	},

	{
		Operation: "currentVisitors",
		Method:    "GET",
		Path:      "/current_visitors",
		Run:       _smokeCase29,
	},
}

func selectedCases() []smokeCase {
	filter := os.Getenv("SCALAR_SMOKE_FILTER")
	if filter == "" {
		return cases
	}
	needles := strings.Split(filter, ",")
	selected := make([]smokeCase, 0, len(cases))
	for _, testCase := range cases {
		for _, needle := range needles {
			needle = strings.TrimSpace(needle)
			if needle == "" {
				continue
			}
			if strings.Contains(testCase.Operation, needle) || strings.Contains(testCase.Path, needle) {
				selected = append(selected, testCase)
				break
			}
		}
	}
	return selected
}

func runCase(testCase smokeCase) (result smokeResult) {
	startedAt := time.Now()
	result = smokeResult{
		Operation: testCase.Operation,
		Method:    testCase.Method,
		Path:      testCase.Path,
		Label:     testCase.Label,
		Status:    "passed",
	}
	defer func() {
		result.DurationMs = time.Since(startedAt).Milliseconds()
		if recovered := recover(); recovered != nil {
			result.Status = "failed"
			result.Error = fmt.Sprint(recovered)
		}
	}()
	testCase.Run()
	return result
}

func main() {
	selected := selectedCases()
	results := make([]smokeResult, len(selected))
	var wg sync.WaitGroup
	for index, testCase := range selected {
		wg.Add(1)
		go func(index int, testCase smokeCase) {
			defer wg.Done()
			results[index] = runCase(testCase)
		}(index, testCase)
	}
	wg.Wait()

	failed := 0
	for _, result := range results {
		if result.Status == "failed" {
			failed++
		}
	}

	report := map[string]interface{}{"total": len(results), "failed": failed, "results": results}
	if reportPath := os.Getenv("SCALAR_SMOKE_REPORT"); reportPath != "" {
		bytes, err := json.Marshal(report)
		if err != nil {
			panic(err)
		}
		if err := os.WriteFile(reportPath, bytes, 0o644); err != nil {
			panic(err)
		}
	} else {
		for _, result := range results {
			suffix := ""
			if result.Label != "" {
				suffix = " [" + result.Label + "]"
			}
			if result.Status == "passed" {
				fmt.Printf("PASS %s%s (%s %s) %dms\n", result.Operation, suffix, result.Method, result.Path, result.DurationMs)
			} else {
				fmt.Fprintf(os.Stderr, "FAIL %s%s (%s %s)\n%s\n", result.Operation, suffix, result.Method, result.Path, result.Error)
			}
		}
		if len(results) == 0 {
			fmt.Fprintln(os.Stderr, "No code samples ran (empty SDK or a SCALAR_SMOKE_FILTER that matched nothing).")
		} else {
			fmt.Printf("\n%d/%d samples passed\n", len(results)-failed, len(results))
		}
	}

	if failed > 0 || len(results) == 0 {
		os.Exit(1)
	}
}
